name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Docker Compose App
        run: |
          docker compose down
          docker compose up -d

      - name: Test App
        run: |
          cd test/
          pip install pytest
          pytest test.py
